name: cb
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy=1.21.2
  - pip
  - pip:
    - tqdm==4.62.3

# to update the environment upon changing the dependencies
# $ conda env update --prefix ./env --file environment.yml --prune

# to recreate the environment 
# conda env create --name recoveredenv --file environment.yml